config/routes.rb
Rails.application.routes.draw do
  get 'drivers/index'
  get 'drivers/new'
  get 'drivers/create'
  get 'drivers/edit'
  get 'drivers/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :drivers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
class Driver < ApplicationRecord
  has_one :license
  accepts_nested_attributes_for :license

  def name
    [first_name, last_name].join(" ")
  end
end

app/models/license.rb
class License < ApplicationRecord
  belongs_to :driver
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController

  before_action :get_driver, only: [:show, :destroy]

  def index
    @drivers = Driver.all
  end

  def show
  end

  def new

    @driver = Driver.new
    @driver.build_license
    render 'new'

  end

  def create
    @driver = Driver.new(driver_params)
    if @driver.save
      redirect_to drivers_url
    else
      render 'new'
    end
  end

  def edit
  end

  def destroy
    @driver.destroy
    redirect_to drivers_url
  end

private

  def get_driver
    @driver = Driver.find(params[:id])
  end

  def driver_params
    params.require(:driver).permit( :first_name, :last_name, license_attributes: [:number, :state])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/create.html.erb
<h1>Drivers#create</h1>
<p>Find me in app/views/drivers/create.html.erb</p>

app/views/drivers/edit.html.erb
<h1>Drivers#edit</h1>
<p>Find me in app/views/drivers/edit.html.erb</p>

app/views/drivers/index.html.erb
<h1>All of the Drivers</h1>

<h3><em>
<ul>
<% @drivers.each do |driver| %>
  <li> <%= link_to driver.name, driver%></li>
  <% if driver.license.present? %>
  <%= driver.license.state %>
  <% end %>
  <%= link_to 'Delete', driver_path(driver), method: :delete, data: { confirm: 'Are you sure???'}%>
<% end %>

</ul>
</em></h3>


<%= link_to "New Driver", new_driver_path %>

app/views/drivers/new.html.erb
<h1>Add a new Driver</h1>
<div>
<%= form_for @driver do |f|%>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %><br>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
</div>

<div>
<%= f.fields_for :license do |license_builder| %>
    <%= license_builder.label :number, "Driver's License Number" %>
    <%= license_builder.text_field :number %><br>

    <%= license_builder.label :state %>
    <%= license_builder.text_field :state %>
<% end %>
</div>

  <%= f.submit %>
<% end %>
<%= link_to "Cancel", drivers_path %>

app/views/drivers/show.html.erb
<h1><%=  @driver.first_name%>'s Page</h1>

<ul>

  <li>First Name: <%= @driver.first_name%></li>
  <li>Last Name: <%= @driver.last_name %></li>
  <% if @driver.license.present? %>
    <li> License Number: <%= @driver.license.number %></li>
    <li> License State: <%= @driver.license.state %></li>
    <% end %>
</ul>

<p> <%= link_to "back to all drivers", drivers_path %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drivers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>